# we are fetching the details from teh official docs of the keras over here
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 25
CLASSES: 4
WEIGHTS: imagenet
LEARNING_RATE: 0.01

